# Generated by Django 3.2.5 on 2021-08-01 17:28

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Вопрос')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='static/img/tours/', verbose_name='Фото')),
                ('thumb', models.ImageField(blank=True, editable=False, upload_to='static/img/tours/')),
            ],
            options={
                'verbose_name': 'Гид',
                'verbose_name_plural': 'Гиды',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=64, verbose_name='Короткое название')),
                ('short_description', tinymce.models.HTMLField(blank=True, verbose_name='Короткое описание')),
                ('card_image', models.ImageField(upload_to='static/img/tours/', verbose_name='Изображение в карточке')),
                ('card_thumb', models.ImageField(blank=True, editable=False, upload_to='static/img/tours/')),
                ('detail_name', tinymce.models.HTMLField(blank=True, verbose_name='Название на детальной странице')),
                ('detail_image', models.ImageField(upload_to='static/img/tours/', verbose_name='Изображение на детальной странице')),
                ('detail_thumb', models.ImageField(blank=True, editable=False, upload_to='static/img/tours/')),
                ('groups_from', models.IntegerField(verbose_name='Размер группы от')),
                ('groups_to', models.IntegerField(blank=True, null=True, verbose_name='Размер группы до')),
                ('duration', models.CharField(max_length=64, verbose_name='Время в туре')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('how_to_find', tinymce.models.HTMLField(blank=True, verbose_name='Как добраться')),
                ('interesting_places', tinymce.models.HTMLField(blank=True, verbose_name='Интересные места')),
                ('video_url', models.CharField(blank=True, max_length=64, verbose_name='Ссылка на видео')),
                ('video_image', models.ImageField(blank=True, upload_to='static/img/tours/', verbose_name='Превью видео')),
                ('video_thumb', models.ImageField(blank=True, editable=False, upload_to='static/img/tours/')),
                ('inventory_text', tinymce.models.HTMLField(blank=True, verbose_name='Что будем брать с собой')),
                ('slug', models.SlugField(blank=True)),
                ('faq_items', models.ManyToManyField(blank=True, default=None, to='tours.FAQItem', verbose_name='Вопросы')),
                ('guides', models.ManyToManyField(blank=True, default=None, to='tours.Guide', verbose_name='Гиды')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
        migrations.CreateModel(
            name='TourStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='static/img/tours/', verbose_name='Изображение')),
                ('thumb', models.ImageField(blank=True, editable=False, upload_to='static/img/tours/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Этап тура',
                'verbose_name_plural': 'Этапы тура',
            },
        ),
        migrations.CreateModel(
            name='TourInventoryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/tours/', verbose_name='Изображение')),
                ('thumb', models.ImageField(blank=True, editable=False, upload_to='static/img/tours/')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_imgs', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Изображение (Что будем брать с собой)',
                'verbose_name_plural': 'Изображения (Что будем брать с собой)',
            },
        ),
        migrations.CreateModel(
            name='TourInterestingPlacesImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/tours/', verbose_name='Изображение')),
                ('thumb', models.ImageField(blank=True, editable=False, upload_to='static/img/tours/')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itimgs', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Изображение (интересные места)',
                'verbose_name_plural': 'Изображения (интересные места)',
            },
        ),
        migrations.CreateModel(
            name='TourHowToFindImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/tours/', verbose_name='Изображение')),
                ('thumb', models.ImageField(blank=True, editable=False, upload_to='static/img/tours/')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='htfimgs', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Изображение (как добраться)',
                'verbose_name_plural': 'Изображения (как добраться)',
            },
        ),
    ]
