# Generated by Django 3.2.5 on 2021-08-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourhowtofindimages',
            options={'ordering': ['-priority'], 'verbose_name': 'Изображение (как добраться)', 'verbose_name_plural': 'Изображения (как добраться)'},
        ),
        migrations.AlterModelOptions(
            name='tourinterestingplacesimages',
            options={'ordering': ['-priority'], 'verbose_name': 'Изображение (интересные места)', 'verbose_name_plural': 'Изображения (интересные места)'},
        ),
        migrations.AlterModelOptions(
            name='tourinventoryimages',
            options={'ordering': ['-priority'], 'verbose_name': 'Изображение (Что будем брать с собой)', 'verbose_name_plural': 'Изображения (Что будем брать с собой)'},
        ),
        migrations.AlterModelOptions(
            name='tourstep',
            options={'ordering': ['priority'], 'verbose_name': 'Этап тура', 'verbose_name_plural': 'Этапы тура'},
        ),
        migrations.AddField(
            model_name='tourstep',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер'),
        ),
    ]
