# Generated by Django 3.2.5 on 2021-08-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20210808_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='video_url',
            field=models.TextField(blank=True, verbose_name='Встроенное видео'),
        ),
    ]
