# Generated by Django 3.2.5 on 2021-09-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tour_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='video_url',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Встроенное видео'),
        ),
    ]
