# Generated by Django 3.2.5 on 2021-08-01 17:28

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='static/img/blog/', verbose_name='Фото')),
                ('thumb', models.ImageField(blank=True, editable=False, upload_to='static/img/blog/')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Короткое описание')),
                ('content1', tinymce.models.HTMLField(blank=True, verbose_name='Контент до слайдера')),
                ('content2', tinymce.models.HTMLField(blank=True, verbose_name='Контент после слайдера')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
            },
        ),
        migrations.CreateModel(
            name='ArticleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/blog/', verbose_name='Изображение')),
                ('thumb', models.ImageField(blank=True, editable=False, upload_to='static/img/blog/')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.article', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Изображение (слайдер)',
                'verbose_name_plural': 'Изображения (слайдер)',
                'ordering': ['-priority'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, to='blog.Tag', verbose_name='Рубрики'),
        ),
    ]
