# Generated by Django 3.2.5 on 2021-08-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-priority'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='article',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Приоритет'),
        ),
    ]
