# Generated by Django 3.2.5 on 2021-08-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20210817_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycard',
            name='custom_link',
            field=models.CharField(blank=True, max_length=64, verbose_name='Своя ссылка'),
        ),
    ]
