# Generated by Django 3.2.5 on 2021-08-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_category', models.CharField(choices=[('inventory', 'Прокат инвентаря'), ('auto', 'Прокат авто'), ('bicycle', 'Прокат велосипедов'), ('scooter', 'Прокат самокатов'), ('moped', 'Прокат мопедов'), ('boat', 'Прокат яхт'), ('aquabike', 'Прокат аквабайков')], default='inventory', max_length=32)),
            ],
        ),
    ]
