# Generated by Django 3.2.5 on 2021-08-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelwithcategory',
            name='base_category',
            field=models.CharField(choices=[('inventory', 'Прокат инвентаря'), ('auto', 'Прокат авто'), ('bicycle', 'Прокат велосипедов'), ('scooter', 'Прокат самокатов'), ('moped', 'Прокат мопедов'), ('boat', 'Прокат яхт'), ('aquabike', 'Прокат аквабайков'), ('sup', 'Прокат сапов')], default='inventory', max_length=32),
        ),
    ]
