# Generated by Django 3.2.5 on 2021-08-01 17:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(blank=True, max_length=64, verbose_name='Форма')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('phone', models.CharField(max_length=64, verbose_name='Телефон')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='Описание')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создание заказа')),
            ],
            options={
                'verbose_name': 'Заявка на обратный звонок',
                'verbose_name_plural': 'Заявки на обратный звонок',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('phone', models.CharField(max_length=64, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=64, verbose_name='Почта')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=64, verbose_name='Адрес')),
                ('comment', models.TextField(blank=True, max_length=64, verbose_name='Комментарий')),
                ('date_from', models.DateField(verbose_name='Бронь от')),
                ('date_to', models.DateField(verbose_name='Бронь до')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создание заказа')),
                ('payment_type', models.CharField(choices=[('bank_card', 'Банковская карта'), ('cash_courier', 'Наличными курьеру'), ('cash_shop', 'Наличными в магазине')], default='cash_shop', max_length=32, verbose_name='Тип оплаты')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('approved_1', 'Подтвержден и ждет оплаты'), ('approved_2', 'Подтвержден и оплачен'), ('delivered', 'Выдан клиенту'), ('await', 'Ожидание возврата инвентаря'), ('finished', 'Выполнен'), ('cancelled', 'Отменен'), ('payment_error', 'Ошибка при оплате')], default='created', max_length=32, verbose_name='Статус')),
                ('total_price', models.IntegerField(blank=True, null=True, verbose_name='Полная цена')),
                ('basket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket.basket', verbose_name='Корзина')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='ProductUnitInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.order', verbose_name='Заказ')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productunit', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
    ]
