# Generated by Django 3.2.5 on 2022-06-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_from',
            field=models.DateTimeField(verbose_name='Бронь от'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_to',
            field=models.DateTimeField(verbose_name='Бронь до'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=64, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='productunitinorder',
            name='price',
            field=models.IntegerField(verbose_name='Цена за час/день'),
        ),
    ]
