# Generated by Django 3.2.5 on 2022-06-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_from',
            field=models.DateTimeField(verbose_name='Бронь от'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_to',
            field=models.DateTimeField(verbose_name='Бронь до'),
        ),
    ]
