# Generated by Django 3.2.5 on 2022-06-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-priority'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_main'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='product',
            name='hour_rate',
            field=models.BooleanField(default=False, verbose_name='Товар с почасовой оплатой'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, related_name='products', to='products.ProductTag', verbose_name='Параметры'),
        ),
        migrations.AlterField(
            model_name='productunitbookingdates',
            name='date_from',
            field=models.DateTimeField(verbose_name='Бронь от'),
        ),
        migrations.AlterField(
            model_name='productunitbookingdates',
            name='date_to',
            field=models.DateTimeField(verbose_name='Бронь до'),
        ),
    ]
