# Generated by Django 3.2.5 on 2022-06-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_hour_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunitbookingdates',
            name='date_from',
            field=models.DateTimeField(verbose_name='Бронь от'),
        ),
        migrations.AlterField(
            model_name='productunitbookingdates',
            name='date_to',
            field=models.DateTimeField(verbose_name='Бронь до'),
        ),
    ]
